image:
  tag: test-latest
replicas: 1

# Deployed datasource flow:
# env override values > config map > pod env vars > application.properties > Spring property > @Value injection >
# Hikari datasource > Read/Write JPA configs > Read/Write repositories > Service Layer > Controller Layer > Endpoints
spring:
  datasource:
    read:
      url: jdbc:mysql://127.0.0.1:3306/rats?useSSL=false&allowPublicKeyRetrieval=true
      username: devuser
      password: Rcal_1995!
    write:
      url: jdbc:mysql://127.0.0.1:3306/rats?useSSL=false&allowPublicKeyRetrieval=true
      username: devuser
      password: Rcal_1995!

cloudsql:
  enabled: true
  instanceConnectionName: noble-helper-469522-j1:us-south1:rcal-mysql-dal

ingress:
  host: api.test.rcal.internal
  tls:
    secretName: test-internal-wildcard-tls
  paths:
  - path: /people/(.*)
    serviceName: rats-backend-ws-people-test-service
    servicePort: 80