# Deployed datasource flow:
# env override values > config map > pod env vars > application.properties > Spring property > @Value injection >
# Hikari datasource > Read/Write JPA configs > Read/Write repositories > Service Layer > Controller Layer > Endpoints
image:
  tag: prod-latest
replicas: 1

spring:
  datasource:
    read:
      url: jdbc:mysql://127.0.0.1:3306/rats?useSSL=false&allowPublicKeyRetrieval=true
      username: devuser
      password: Rcal_1995!
    write:
      url: jdbc:mysql://10.10.5.55:6446/rats?useSSL=false&allowPublicKeyRetrieval=true
      username: rat
      password: Rat_2021!

cloudsql:
  enabled: true
  instanceConnectionName: noble-helper-469522-j1:us-south1:rcal-mysql-dal-rats

ingress:
  enabled: true
  host: people.rcal.internal
  tls:
    secretName: prod-internal-wildcard-tls
  paths:
    - path: /api/(.*)
      serviceName: rats-backend-ws-people-prod-service
      servicePort: 80